package com.project.enums;

public enum AuditModule { USER_MODULE, ACCOUNT_MODULE, TRANSFER_MODULE, LOAN_MODULE, INVESTMENT_MODULE, KYC_MODULE, COMPLIANCE_MODULE, REPORT_MODULE, NOTIFICATION_MODULE }
